export const COURSES_LIST_REQUEST = 'COURSES_LIST_REQUEST'
export const COURSES_LIST_SUCCESS = 'COURSES_LIST_SUCCESS'
export const COURSES_LIST_FAIL = 'COURSES_LIST_FAIL'

export const COURSE_DETAIL_REQUEST = 'COURSE_DETAIL_REQUEST'
export const COURSE_DETAIL_SUCCESS = 'COURSE_DETAIL_SUCCESS'
export const COURSE_DETAIL_FAIL = 'COURSE_DETAIL_FAIL'


